# Generated by Django 4.2 on 2023-04-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('grade', models.CharField(max_length=30)),
                ('specialty', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
                ('education', models.CharField(max_length=30)),
                ('experience', models.TextField()),
                ('title', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
